name: Build Project

on:
  push:
    branches:
      - main # Выполнять сборку при пуше в ветку main
  pull_request:
    branches:
      - main # Выполнять сборку для PR в ветку main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Проверить репозиторий
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установить Git (если нужно)
      - name: Install Git
        run: sudo apt update && sudo apt install -y git

      # 3. Установить Node.js и npm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Укажите нужную версию Node.js

      # 4. Установить зависимости
      - name: Install dependencies
        run: npm install

      # 5. Собрать проект
      - name: Build the project
        run: npm run build

      # 6. (Необязательно) Сохранить артефакты сборки
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./dist # Путь к папке с собранным проектом
